import type { Metadata } from "next";
import "./globals.css";
import { suit, suite } from "./font";

export const metadata: Metadata = {
  title: "Cupfee Deal",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${suite.variable} ${suit.variable}`}>
      <body className="h-[100dvh] max-w-[440px] mx-auto bg-white">
        {children}
      </body>
    </html>
  );
}
